image:
  tag: e953c0b

env:
  DB_HOST: gitops-example-dev-aurora-cluster.cluster-c0up5hdxofsf.us-west-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_DATABASE: api
  DB_USER: api
  DB_PASSWORD: -ew2vC[k3LO!3L!u+U7Nd*sJl2!w)6S-FLRXz--*

ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - name: "gitops-example-dev.foo.bar"
      paths:
        - /api(/|$)(.*)
