image:
  tag: 5631b0d

env:
  DB_HOST: gitops-example-dev-aurora-cluster.cluster-c0up5hdxofsf.us-west-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_DATABASE: api
  DB_USER: api
  DB_PASSWORD: api

ingress:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - name: "gitops-example-dev.foo.bar"
      paths:
        - /api(/|$)(.*)
