version: '3.8'
services:

  web_app:
    build:
      context: ../web_app
    environment:
      API_HOST: "api"
      API_PORT: "5000"
      FLASK_DEBUG: 1
      PYTHONUNBUFFERED: 1
    ports:
      - target: 5000
        published: $WEB_APP_PORT
        mode: host
    volumes:
      - ../web_app/src:/app
    depends_on:
      - db
    restart: unless-stopped

  api:
    build:
      context: ../api
    environment:
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      DB_HOST: "db"
      DB_PORT: "5432"
      FLASK_DEBUG: 1
      PYTHONUNBUFFERED: 1
    ports:
      - target: 5000
        published: $API_PORT
        mode: host
    volumes:
      - ../api/src:/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  db_admin:
    image: dpage/pgadmin4:6.2
    environment:
      PGADMIN_DEFAULT_EMAIL: $DB_ADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $DB_ADMIN_PASSWORD
    ports:
      - target: 80
        published: $DB_ADMIN_PORT
        mode: host
    depends_on:
      - db
    volumes:
      - db_admin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  db_data:
  db_init_control:
  db_admin_data:
