image:
  repository: adiffpirate/gitops-example-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:
  DB_USER: test
  DB_PASSWORD: test
  DB_DATABASE: postgres
  DB_HOST: ""
  DB_PORT: "5432"

podAnnotations: {}

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 80
