name: CD

on:
  push:
    # branches: ["master"]

jobs:

  #-------------#
  # Docker Push #
  #-------------#

  docker-push:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        application: ["webapp", "api"]

    steps:
      - uses: actions/checkout@v3
        name: Checkout source code
      
      - uses: docker/setup-qemu-action@v2
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v4
        name: Build
        with:
          context: dev/${{ matrix.application }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitops-example-${{ matrix.application }}:${{ steps.vars.outputs.tag }}

  #----------------#
  # Update DEV env #
  #----------------#

  update-dev-env:
    runs-on: ubuntu-latest
    needs: docker-push
    
    strategy:
      matrix:
        application: ["webapp", "api"]

    steps:
      - uses: actions/checkout@v3
        name: Checkout source code

      - name: Get tag
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Update tag on values
        working-directory: ops/environments/dev/05_applications
        env:
          APP: ${{ matrix.application }}
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          sed -i "s/tag: .*/tag: ${TAG}/" ${APP}_values.yaml

      - name: Commit and push changes
        env:
          APP: ${{ matrix.application }}
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Bump '${APP}' application tag to ${TAG} on DEV environment"
          git push
