name: CI Dev

on:
  push:
    # branches: ["master"]

jobs:

  #-------------#
  # Docker Push #
  #-------------#

  docker-push:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        application: ["webapp", "api"]

    steps:
      - uses: actions/checkout@v3
        name: Checkout source code
      
      - uses: docker/setup-qemu-action@v2
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v4
        name: Build
        with:
          context: dev/${{ matrix.application }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitops-example-${{ matrix.application }}:${{ steps.vars.outputs.tag }}
